const jobs=[
 {title:'IT Project Manager',company:'Edenred',initial:'E',fit:91,location:'Bucharest',mode:'Hybrid',type:'Permanent',age:2,remote:false,b2b:false,repost:false,status:'new',pros:['Experienta solida in proiecte IT complexe si medii reglementate','Potrivire buna pe stakeholder management si vendor governance'],risks:['Contract permanent; nu este B2B'],url:null},
 {title:'Agile Project Manager',company:'DKV Mobility',initial:'D',fit:87,location:'Romania',mode:'Remote',type:'B2B posibil',age:4,remote:true,b2b:true,repost:true,status:'review',pros:['Remote din Romania','Experienta Agile relevanta'],risks:['Forma B2B trebuie confirmata'],url:null},
 {title:'Technical Project Manager',company:'European Dynamics',initial:'ED',fit:84,location:'Brussels',mode:'Hybrid',type:'B2B',age:6,remote:false,b2b:true,repost:false,status:'review',pros:['Experienta directa cu institutii europene','PM² si guvernanta formala relevante'],risks:['Prezenta periodica in Bruxelles'],url:null},
 {title:'Service Delivery Manager',company:'Allianz Services',initial:'A',fit:81,location:'Bucharest',mode:'Hybrid',type:'Permanent',age:8,remote:false,b2b:false,repost:false,status:'new',pros:['Experienta ITIL si SLA','Context enterprise relevant'],risks:['Poate cere ServiceNow'],url:null},
 {title:'Project Manager — Digital Platforms',company:'SoftServe',initial:'S',fit:76,location:'Europe',mode:'Remote',type:'B2B',age:11,remote:true,b2b:true,repost:true,status:'review',pros:['Remote in Europa','Echipe distribuite'],risks:['Cerinte tehnice neclare'],url:null},
 {title:'Senior Scrum Master',company:'Mantu',initial:'M',fit:69,location:'Romania',mode:'Remote',type:'B2B',age:15,remote:true,b2b:true,repost:false,status:'review',pros:['Remote si B2B'],risks:['Prea concentrat pe Scrum Master'],url:null}
];
const applications=[{title:'Project Manager',company:'Atos / Bull',initial:'A',fit:90,location:'Timisoara',mode:'Hybrid',type:'Aplicat',age:24,remote:false,b2b:false,repost:false,pros:['Aplicare inregistrata la 2 septembrie 2026','Referinta: 540300'],risks:['Status de verificat la doua saptamani'],url:null}];
const defaultSources=[
 {category:'Site-uri de cariere',name:'Allianz Careers',url:'https://careers.allianz.com/',active:true},{category:'Site-uri de cariere',name:'SoftServe Careers',url:'https://career.softserveinc.com/',active:true},{category:'ATS publice',name:'Workable',url:'https://jobs.workable.com/',active:true},{category:'ATS publice',name:'Ashby',url:'https://www.ashbyhq.com/careers',active:true},{category:'Remote si B2B',name:'Remote.co',url:'https://remote.co/remote-jobs/',active:true},{category:'Contractori UE / NATO',name:'European Dynamics',url:'https://www.eurodyn.com/careers/',active:true}
];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let sources=JSON.parse(localStorage.getItem('managedSources')||'null')||defaultSources;let view='jobs',active='all',visible=[];
function baseRows(){return view==='applications'?applications:view==='review'?jobs.filter(j=>j.status==='review'):jobs}
function setCounts(){const high=jobs.filter(j=>j.fit>=80).length,remote=jobs.filter(j=>j.remote).length,b2b=jobs.filter(j=>j.b2b).length;$('#countJobs').textContent=jobs.length;$('#countReview').textContent=jobs.filter(j=>j.status==='review').length;$('#countApplications').textContent=applications.length;$('#metricJobs').textContent=jobs.length;$('#metricHigh').textContent=high;$('#metricReposts').textContent=jobs.filter(j=>j.repost).length;$('#metricRemote').textContent=remote;const base=baseRows();$('#filterAll').textContent=base.length;$('#filterHigh').textContent=base.filter(j=>j.fit>=80).length;$('#filterRemote').textContent=base.filter(j=>j.remote).length;$('#filterB2b').textContent=base.filter(j=>j.b2b).length}
function renderJobs(){const q=$('#search').value.toLowerCase();visible=baseRows().filter(j=>(active==='all'||active==='high'&&j.fit>=80||active==='remote'&&j.remote||active==='b2b'&&j.b2b)&&(`${j.title} ${j.company}`.toLowerCase().includes(q)));visible.sort($('#sort').value==='fit'?(a,b)=>b.fit-a.fit:(a,b)=>a.age-b.age);$('.table-head').innerHTML='<span>ROL</span><span>FIT</span><span>MOD DE LUCRU</span><span>PUBLICAT</span><span></span>';$('#jobList').innerHTML=visible.map((j,i)=>`<article class="job" data-index="${i}"><div class="role"><span class="company-logo">${j.initial}</span><div><strong>${j.title}</strong><div class="meta"><span>${j.company} · ${j.location}</span>${j.repost?'<span class="tag repost">Repostare</span>':''}<span class="tag">${j.type}</span></div></div></div><span class="score ${j.fit>=80?'high':'mid'}">${j.fit}%</span><span class="mode">${j.mode}</span><span class="posted">acum ${j.age}h</span><span class="chev">›</span></article>`).join('');$('#empty').hidden=visible.length>0;$$('.job').forEach(el=>el.onclick=()=>openJob(visible[+el.dataset.index]))}
function saveSources(){localStorage.setItem('managedSources',JSON.stringify(sources))}
function renderSources(){const q=$('#sourceSearch').value.toLowerCase(),sort=$('#sourceSort').value;let rows=sources.filter(s=>`${s.name} ${s.category}`.toLowerCase().includes(q));rows.sort(sort==='name'?(a,b)=>a.name.localeCompare(b.name):(a,b)=>Number(b.active)-Number(a.active)||a.name.localeCompare(b.name));const groups=Object.groupBy?Object.groupBy(rows,s=>s.category):rows.reduce((a,s)=>((a[s.category]??=[]).push(s),a),{});$('.table-head').innerHTML='<span>LISTE DE SURSE</span>';$('#jobList').innerHTML=Object.entries(groups).map(([category,items])=>`<details class="source-group" open><summary><strong>${category}</strong><small>${items.length} surse</small></summary><div class="source-items">${items.map(s=>`<div class="source-item"><a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.name} ↗</a><label class="switch-label"><input class="source-toggle" type="checkbox" data-url="${s.url}" ${s.active?'checked':''}> Activa</label><button class="source-remove" data-url="${s.url}">Elimina</button></div>`).join('')}</div></details>`).join('')+'<form id="addSourceForm" class="add-form" hidden><input id="newSourceName" required placeholder="Numele sursei"><input id="newSourceUrl" required type="url" placeholder="https://..."><select id="newSourceCategory"><option>Site-uri de cariere</option><option>ATS publice</option><option>Remote si B2B</option><option>Contractori UE / NATO</option></select><button class="primary">Salveaza</button></form>';$('#empty').hidden=rows.length>0;$$('.source-toggle').forEach(x=>x.onchange=()=>{const s=sources.find(v=>v.url===x.dataset.url);s.active=x.checked;saveSources()});$$('.source-remove').forEach(x=>x.onclick=()=>{sources=sources.filter(v=>v.url!==x.dataset.url);saveSources();renderSources()});$('#addSourceForm').onsubmit=e=>{e.preventDefault();sources.push({name:$('#newSourceName').value,url:$('#newSourceUrl').value,category:$('#newSourceCategory').value,active:true});saveSources();renderSources()}}
function render(){setCounts();view==='sources'?renderSources():!['criteria','rules'].includes(view)&&renderJobs()}
function openJob(j){$('#drawerTitle').textContent=j.title;$('#drawerCompany').textContent=`${j.company} · ${j.location}`;$('#drawerScore').textContent=`${j.fit}%`;$('#pros').innerHTML=j.pros.map(x=>`<li>${x}</li>`).join('');$('#risks').innerHTML=j.risks.map(x=>`<li>${x}</li>`).join('');const a=$('#applyLink');if(j.url){a.href=j.url;a.classList.remove('disabled')}else{a.removeAttribute('href');a.textContent='Link de aplicare indisponibil';a.classList.add('disabled')}$('#drawer').classList.add('open');$('#scrim').classList.add('open')}
function close(){ $('#drawer').classList.remove('open');$('#scrim').classList.remove('open')}
$$('.nav[data-view]').forEach(btn=>btn.onclick=()=>{$$('.nav[data-view]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');view=btn.dataset.view;active='all';$('h1').textContent={jobs:'Joburi noi',review:'De evaluat',applications:'Aplicari',criteria:'Criterii de selectie',sources:'Surse',rules:'Reguli si filtre'}[view];$('.summary').hidden=view!=='jobs';$('.toolbar:not(.source-toolbar)').hidden=!['jobs','review'].includes(view);$('#sourceToolbar').hidden=view!=='sources';$('#criteriaPanel').hidden=view!=='criteria';$('#rulesPanel').hidden=view!=='rules';$('.workspace').hidden=['criteria','rules'].includes(view);render()});
$$('.filter').forEach(btn=>btn.onclick=()=>{$('.filter.active').classList.remove('active');btn.classList.add('active');active=btn.dataset.filter;render()});$('#search').oninput=render;$('#sort').onchange=render;$('#sourceSearch').oninput=renderSources;$('#sourceSort').onchange=renderSources;$('#addSource').onclick=()=>{const f=$('#addSourceForm');f.hidden=!f.hidden;if(!f.hidden)$('#newSourceName').focus()};$('#closeDrawer').onclick=close;$('#scrim').onclick=close;document.onkeydown=e=>e.key==='Escape'&&close();function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}$('#runSearch').onclick=()=>toast('Verificare pornita.');$('#saveCriteria').onclick=()=>{localStorage.setItem('selectionCriteria',JSON.stringify({freshness:$('#freshness').value,fit:$('#fitThreshold').value,reposts:$('#keepReposts').checked}));toast('Criteriile au fost salvate.')};$('#saveRules').onclick=()=>toast('Regulile au fost salvate.');render();
