const jobs=[
 {title:'IT Project Manager',company:'Edenred',initial:'E',fit:91,location:'Bucharest',mode:'Hybrid',type:'Permanent',age:2,remote:false,b2b:false,repost:false,status:'new',pros:['Experienta solida in proiecte IT complexe si medii reglementate','Potrivire buna pe stakeholder management si vendor governance'],risks:['Contract permanent; nu este B2B'],url:null},
 {title:'Agile Project Manager',company:'DKV Mobility',initial:'D',fit:87,location:'Romania',mode:'Remote',type:'B2B posibil',age:4,remote:true,b2b:true,repost:true,status:'review',pros:['Remote din Romania','Experienta Agile relevanta'],risks:['Forma B2B trebuie confirmata'],url:null},
 {title:'Technical Project Manager',company:'European Dynamics',initial:'ED',fit:84,location:'Brussels',mode:'Hybrid',type:'B2B',age:6,remote:false,b2b:true,repost:false,status:'review',pros:['Experienta directa cu institutii europene','PM2 si guvernanta formala relevante'],risks:['Prezenta periodica in Bruxelles'],url:null},
 {title:'Service Delivery Manager',company:'Allianz Services',initial:'A',fit:81,location:'Bucharest',mode:'Hybrid',type:'Permanent',age:8,remote:false,b2b:false,repost:false,status:'new',pros:['Experienta ITIL si SLA','Context enterprise relevant'],risks:['Poate cere ServiceNow'],url:null},
 {title:'Project Manager - Digital Platforms',company:'SoftServe',initial:'S',fit:76,location:'Europe',mode:'Remote',type:'B2B',age:11,remote:true,b2b:true,repost:true,status:'review',pros:['Remote in Europa','Echipe distribuite'],risks:['Cerinte tehnice neclare'],url:null},
 {title:'Senior Scrum Master',company:'Mantu',initial:'M',fit:69,location:'Romania',mode:'Remote',type:'B2B',age:15,remote:true,b2b:true,repost:false,status:'review',pros:['Remote si B2B'],risks:['Prea concentrat pe Scrum Master'],url:null}
];
const applications=[{title:'Project Manager',company:'Atos / Bull',initial:'A',fit:90,location:'Timisoara',mode:'Hybrid',type:'Aplicat',age:24,remote:false,b2b:false,repost:false,pros:['Aplicare inregistrata la 2 septembrie 2026','Referinta: 540300'],risks:['Status de verificat la doua saptamani'],url:null}];
const defaultSources=[
 {category:'Site-uri de cariere',name:'Allianz Careers',url:'https://careers.allianz.com/',active:true,priority:1},{category:'Site-uri de cariere',name:'SoftServe Careers',url:'https://career.softserveinc.com/',active:true,priority:2},{category:'ATS publice',name:'Workable',url:'https://jobs.workable.com/',active:true,priority:3},{category:'ATS publice',name:'Ashby',url:'https://www.ashbyhq.com/careers',active:true,priority:4},{category:'Remote si B2B',name:'Remote.co',url:'https://remote.co/remote-jobs/',active:true,priority:5},{category:'Contractori UE / NATO',name:'European Dynamics',url:'https://www.eurodyn.com/careers/',active:true,priority:null}
];
const defaultCriteria={rolePm:true,roleDelivery:true,roleService:true,roleScrum:true,workRemote:true,workHybrid:true,freshness:'24',fitThreshold:'80',keepReposts:true,rateMin:'250',rateMax:'650',immediateStart:true,exclusions:['Star Storage si companiile grupului','Implementari ERP care cer experienta specializata ampla','Roluri non-IT']};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
let sources=(JSON.parse(localStorage.getItem('managedSources')||'null')||defaultSources).map(s=>({...s,priority:Number.isInteger(s.priority)?s.priority:null}));
let savedCriteria=JSON.parse(localStorage.getItem('selectionCriteria')||'null')||defaultCriteria;
let draftExclusions=[...(savedCriteria.exclusions||[])],view='jobs',active='all',visible=[];

function baseRows(){return view==='applications'?applications:view==='review'?jobs.filter(j=>j.status==='review'):jobs}
function setCounts(){const high=jobs.filter(j=>j.fit>=80).length,remote=jobs.filter(j=>j.remote).length,b2b=jobs.filter(j=>j.b2b).length;$('#countJobs').textContent=jobs.length;$('#countReview').textContent=jobs.filter(j=>j.status==='review').length;$('#countApplications').textContent=applications.length;$('#metricJobs').textContent=jobs.length;$('#metricHigh').textContent=high;$('#metricReposts').textContent=jobs.filter(j=>j.repost).length;$('#metricRemote').textContent=remote;const base=baseRows();$('#filterAll').textContent=base.length;$('#filterHigh').textContent=base.filter(j=>j.fit>=80).length;$('#filterRemote').textContent=base.filter(j=>j.remote).length;$('#filterB2b').textContent=base.filter(j=>j.b2b).length}
function renderJobs(){const q=$('#search').value.toLowerCase();visible=baseRows().filter(j=>(active==='all'||active==='high'&&j.fit>=80||active==='remote'&&j.remote||active==='b2b'&&j.b2b)&&(`${j.title} ${j.company}`.toLowerCase().includes(q)));visible.sort($('#sort').value==='fit'?(a,b)=>b.fit-a.fit:(a,b)=>a.age-b.age);$('.table-head').innerHTML='<span>ROL</span><span>FIT</span><span>MOD DE LUCRU</span><span>PUBLICAT</span><span></span>';$('#jobList').innerHTML=visible.map((j,i)=>`<article class="job" data-index="${i}"><div class="role"><span class="company-logo">${j.initial}</span><div><strong>${j.title}</strong><div class="meta"><span>${j.company} · ${j.location}</span>${j.repost?'<span class="tag repost">Repostare</span>':''}<span class="tag">${j.type}</span></div></div></div><span class="score ${j.fit>=80?'high':'mid'}">${j.fit}%</span><span class="mode">${j.mode}</span><span class="posted">acum ${j.age}h</span><span class="chev">›</span></article>`).join('');$('#empty').hidden=visible.length>0;$$('.job').forEach(el=>el.onclick=()=>openJob(visible[+el.dataset.index]))}
function normalizePriorities(){sources.filter(s=>s.priority!==null).sort((a,b)=>a.priority-b.priority).forEach((s,i)=>s.priority=i+1)}
function saveSources(){localStorage.setItem('managedSources',JSON.stringify(sources))}
function renderSources(){normalizePriorities();const selected=sources.filter(s=>s.priority!==null).length;$('#priorityCount').textContent=`${selected}/5`;const q=$('#sourceSearch').value.toLowerCase(),sort=$('#sourceSort').value;let rows=sources.filter(s=>`${s.name} ${s.category}`.toLowerCase().includes(q));rows.sort((a,b)=>{if(a.priority!==null||b.priority!==null)return(a.priority??99)-(b.priority??99);return sort==='name'?a.name.localeCompare(b.name):Number(b.active)-Number(a.active)||a.name.localeCompare(b.name)});const groups=Object.groupBy?Object.groupBy(rows,s=>s.category):rows.reduce((a,s)=>((a[s.category]??=[]).push(s),a),{});$('.table-head').innerHTML='<span>LISTE DE SURSE</span>';$('#jobList').innerHTML=Object.entries(groups).map(([category,items])=>`<details class="source-group" open><summary><strong>${category}</strong><small>${items.length} surse</small></summary><div class="source-items">${items.map(s=>`<div class="source-item"><div><a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.name} ↗</a>${s.priority!==null?`<small class="priority-badge">Prioritatea ${s.priority}</small>`:''}</div><label class="priority-check"><input class="source-priority" type="checkbox" data-url="${s.url}" ${s.priority!==null?'checked':''} ${selected>=5&&s.priority===null?'disabled':''}> Prioritara</label><label class="switch-label"><input class="source-toggle" type="checkbox" data-url="${s.url}" ${s.active?'checked':''}> Activa</label><button class="source-remove" data-url="${s.url}">Elimina</button></div>`).join('')}</div></details>`).join('')+'<form id="addSourceForm" class="add-form" hidden><input id="newSourceName" required placeholder="Numele sursei"><input id="newSourceUrl" required type="url" placeholder="https://..."><select id="newSourceCategory"><option>Site-uri de cariere</option><option>ATS publice</option><option>Remote si B2B</option><option>Contractori UE / NATO</option></select><button class="primary">Salveaza</button></form>';$('#empty').hidden=rows.length>0;$$('.source-priority').forEach(x=>x.onchange=()=>{const s=sources.find(v=>v.url===x.dataset.url);if(x.checked){const count=sources.filter(v=>v.priority!==null).length;if(count>=5){x.checked=false;toast('Poti selecta maximum 5 surse prioritare.');return}s.priority=count+1}else{s.priority=null}normalizePriorities();renderSources()});$$('.source-toggle').forEach(x=>x.onchange=()=>{sources.find(v=>v.url===x.dataset.url).active=x.checked;saveSources()});$$('.source-remove').forEach(x=>x.onclick=()=>{sources=sources.filter(v=>v.url!==x.dataset.url);normalizePriorities();saveSources();renderSources()});$('#addSourceForm').onsubmit=e=>{e.preventDefault();sources.push({name:$('#newSourceName').value,url:$('#newSourceUrl').value,category:$('#newSourceCategory').value,active:true,priority:null});saveSources();renderSources()}}
function currentCriteria(){const c={};['rolePm','roleDelivery','roleService','roleScrum','workRemote','workHybrid','keepReposts','immediateStart'].forEach(id=>c[id]=$('#'+id).checked);c.freshness=Number($('#freshness').value);c.fitThreshold=Number($('#fitThreshold').value);c.exclusions=[...draftExclusions];return c}
function previewCriteria(){const c=currentCriteria();const rows=jobs.filter(j=>{const t=j.title.toLowerCase();const role=t.includes('scrum')?c.roleScrum:t.includes('service')?c.roleService:t.includes('delivery')||t.includes('technical')?c.roleDelivery:c.rolePm;const mode=j.remote?c.workRemote:j.mode.toLowerCase()==='hybrid'?c.workHybrid:false;const fresh=j.age<=c.freshness;const repost=c.keepReposts||!j.repost;const excluded=c.exclusions.some(x=>{const q=x.toLowerCase();return(q.includes('star storage')&&j.company.toLowerCase().includes('star storage'))||(q.includes('erp')&&t.includes('erp'))||(q.includes('non-it')&&!t.match(/project|scrum|service|delivery|technical|it/))});return role&&mode&&fresh&&repost&&!excluded});$('#metricJobs').textContent=rows.length;$('#metricHigh').textContent=rows.filter(j=>j.fit>=c.fitThreshold).length;$('#metricReposts').textContent=rows.filter(j=>j.repost).length;$('#metricRemote').textContent=rows.filter(j=>j.remote).length;$('#metricHigh').closest('article').querySelector('em').textContent=`>= ${c.fitThreshold}%`}
function render(){setCounts();if(view==='criteria')previewCriteria();else if(view==='sources')renderSources();else renderJobs()}
function openJob(j){$('#drawerTitle').textContent=j.title;$('#drawerCompany').textContent=`${j.company} · ${j.location}`;$('#drawerScore').textContent=`${j.fit}%`;$('#pros').innerHTML=j.pros.map(x=>`<li>${x}</li>`).join('');$('#risks').innerHTML=j.risks.map(x=>`<li>${x}</li>`).join('');const a=$('#applyLink');a.textContent=j.url?'Deschide jobul ↗':'Link de aplicare indisponibil';if(j.url){a.href=j.url;a.classList.remove('disabled')}else{a.removeAttribute('href');a.classList.add('disabled')}$('#drawer').classList.add('open');$('#scrim').classList.add('open')}
function close(){$('#drawer').classList.remove('open');$('#scrim').classList.remove('open')}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function markCriteriaDirty(){$('#criteriaState').textContent='Modificari nesalvate';$('#criteriaState').classList.add('dirty');previewCriteria()}
function renderExclusions(){$('#selectedExclusions').innerHTML=draftExclusions.length?draftExclusions.map((x,i)=>`<button type="button" class="exclusion-chip" data-index="${i}">${x}<span aria-hidden="true">×</span></button>`).join(''):'<span class="empty-selection">Nicio excludere selectata.</span>';$$('.exclusion-chip').forEach(x=>x.onclick=()=>{draftExclusions.splice(+x.dataset.index,1);markCriteriaDirty();renderExclusions()})}
function loadCriteria(){const c=savedCriteria;['rolePm','roleDelivery','roleService','roleScrum','workRemote','workHybrid','keepReposts','immediateStart'].forEach(id=>$('#'+id).checked=c[id]??defaultCriteria[id]);$('#freshness').value=c.freshness||'24';$('#fitThreshold').value=c.fitThreshold||c.fit||'80';$('#rateMin').value=c.rateMin||'250';$('#rateMax').value=c.rateMax||'650';renderExclusions()}

$$('.nav[data-view]').forEach(btn=>btn.onclick=()=>{$$('.nav[data-view]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');view=btn.dataset.view;active='all';$('h1').textContent={jobs:'Joburi noi',review:'De evaluat',applications:'Aplicari',criteria:'Criterii de selectie',sources:'Surse'}[view];$('.summary').hidden=!['jobs','criteria'].includes(view);$('.toolbar:not(.source-toolbar)').hidden=!['jobs','review'].includes(view);$('#sourceToolbar').hidden=view!=='sources';$('#sourcePriorityInfo').hidden=view!=='sources';$('#criteriaPanel').hidden=view!=='criteria';$('.workspace').hidden=view==='criteria';$('#runSearch').hidden=view==='criteria';render()});
$$('.filter').forEach(btn=>btn.onclick=()=>{$('.filter.active').classList.remove('active');btn.classList.add('active');active=btn.dataset.filter;render()});
$('#search').oninput=render;$('#sort').onchange=render;$('#sourceSearch').oninput=renderSources;$('#sourceSort').onchange=renderSources;$('#addSource').onclick=()=>{const f=$('#addSourceForm');f.hidden=!f.hidden;if(!f.hidden)$('#newSourceName').focus()};$('#saveSourcePriorities').onclick=()=>{saveSources();toast('Prioritatile surselor au fost salvate.')};$('#closeDrawer').onclick=close;$('#scrim').onclick=close;document.onkeydown=e=>e.key==='Escape'&&close();$('#runSearch').onclick=()=>toast('Verificare pornita.');
$('#criteriaPanel').addEventListener('change',markCriteriaDirty);$('#criteriaPanel').addEventListener('input',markCriteriaDirty);$('#exclusionSuggestions').onchange=e=>{if(e.target.value&&!draftExclusions.includes(e.target.value)){draftExclusions.push(e.target.value);markCriteriaDirty();renderExclusions()}e.target.value=''};
$('#saveCriteria').onclick=()=>{const c={};['rolePm','roleDelivery','roleService','roleScrum','workRemote','workHybrid','keepReposts','immediateStart'].forEach(id=>c[id]=$('#'+id).checked);c.freshness=$('#freshness').value;c.fitThreshold=$('#fitThreshold').value;c.rateMin=$('#rateMin').value;c.rateMax=$('#rateMax').value;c.exclusions=[...draftExclusions];savedCriteria=c;localStorage.setItem('selectionCriteria',JSON.stringify(c));$('#criteriaState').textContent='Preferinte salvate';$('#criteriaState').classList.remove('dirty');toast('Preferintele au fost salvate.')};
loadCriteria();render();
